/*
Weston Jones 
CS 355 Database Systems 
Section 602 
Assignment 4
4/29/20
*/

--Question 1
SELECT MEMBER.MID, MEMBER.NAME, MEMBER.STARTDATE
FROM MEMBER
INNER JOIN CLUB ON MEMBER.CLUBID = CLUB.CID
WHERE CLUB.CITY = 'Kenosha' AND CLUB.STATE = 'WI'
ORDER BY MEMBER.STARTDATE DESC;

--Question 2
SELECT CLASS.CLID
FROM REGISTRATION
INNER JOIN MEMBER ON MEMBER.MID = REGISTRATION.MEMBERID
INNER JOIN CLASS ON CLASS.CLID = REGISTRATION.CLASSID
WHERE MEMBER.NAME = 'Yao';

--Question 3
SELECT COUNT(MID), AVG(MONTHLYFEE)
FROM MEMBER
WHERE MONTHLYFEE <= 45;

--Question 4
SELECT CLID, TITLE
FROM CLASS
WHERE CLID NOT IN (
    SELECT CLASSID 
    FROM REGISTRATION
)
ORDER BY TITLE ASC;

--Question 5
SELECT MIN(MEMBER.AGE)
FROM REGISTRATION
INNER JOIN MEMBER ON MEMBER.MID = REGISTRATION.MEMBERID
INNER JOIN CLASS ON CLASS.CLID = REGISTRATION.CLASSID
WHERE CLASS.TITLE = 'Cardio';

--QUestion 6
SELECT MEMBERID, COUNT(CLASSID)
FROM REGISTRATION
GROUP BY MEMBERID
HAVING COUNT(CLASSID)>=3;

--Question 7
SELECT CLUBID, MAX(AGE)
FROM MEMBER
GROUP BY CLUBID
ORDER BY CLUBID;

--Question 8
SELECT CLUB.CID, COUNT(MEMBER.MID)
FROM CLUB
INNER JOIN MEMBER ON CLUB.CID = MEMBER.CLUBID
WHERE CLUB.STATE = 'IL'
GROUP BY CLUB.CID
ORDER BY COUNT(MEMBER.MID) ASC;
