/*
Weston Jones 
CS 355 Database Systems 
Section 602 
Assignment 3
4/22/20
*/

--QUESTION 1
SELECT TITLE, PRICE FROM BOOK
WHERE YEAR < 2015 AND AUTHOR='Alice Steen'
ORDER BY YEAR DESC

--QUESTION 2
SELECT NAME FROM STORE 
WHERE NAME LIKE 'Book%'
ORDER BY NAME ASC

--QUESTION 3
SELECT YEAR, COUNT(BID) AS NumberOfBooks
FROM BOOK
GROUP BY YEAR
ORDER BY YEAR ASC

--QUESTION 4
SELECT AUTHOR, AVG(PRICE) AS AveragePrice
FROM BOOK
GROUP BY AUTHOR
ORDER BY AveragePrice ASC

--QUESTION 5
SELECT STOREID, COUNT(ORDERID) AS NumberOfOrders
FROM BOOKORDER
GROUP BY STOREID
ORDER BY STOREID ASC

--QUESTION 6
SELECT STORE.SID, STORE.NAME
FROM STORE 
INNER JOIN BOOKORDER ON STORE.SID=BOOKORDER.STOREID
WHERE BOOKORDER.ORDERDATE BETWEEN'01-APRIL-2019' AND '30-APRIL-2019'
GROUP BY STORE.SID, STORE.NAME
ORDER BY SID ASC

--QUESTION 7
SELECT BOOK.TITLE
FROM BOOKORDER
INNER JOIN BOOK ON BOOK.BID=BOOKORDER.BOOKID
INNER JOIN STORE ON STORE.SID=BOOKORDER.STOREID
WHERE STORE.STATE='NY'
GROUP BY BOOK.TITLE
ORDER BY BOOK.TITLE ASC

--QUESTION 8
SELECT BOOK.TITLE, COUNT(BOOKORDER.ORDERID) AS NumberOfOrders
FROM BOOKORDER
INNER JOIN BOOK ON BOOK.BID=BOOKORDER.BOOKID
GROUP BY BOOK.TITLE
ORDER BY NumberOfOrders DESC
